### PR TITLE
Update to React 15

### PR DESCRIPTION
**Pull request by magnars**
I have now perused the React 15 release notes and found no necessary changes. I have also tested this version with my own projects (as well as devcards). This seems to be a straightforward upgrade. And there's quite the list of bugfixes and improvements bundled with it.

### CODE REVIEW

**Comment by magnars** [comment]
I have now used this for a couple days on two projects with no issue. Hope you have some time in between Arachne work to take a look, @levand. :)

**Comment by magnars** [comment]
I see Facebook has released a still newer version, 15.1.0. Maybe we would like to skip straight to that? I can build a local version with that release and report back if I encounter any issues.

**Comment by magnars** [comment]
I see no issues with 15.1.0 in my two large quiescent projects. Pushed.

**Comment by magnars** [comment]
One bonus of 15.1.0 is that React now complains if you forget the properties-map: `(d/h1 "hello")` used to be quietly ignored, but now creates a warning.

**Comment by zentrope** [comment]
I'm interested in using this. How do I merge this in to a checkout of master?

**Pull request merged**
